
InputDNA = "GGGACTTTGGACTTTATAAGGACTTTCCCGGCGGACTTTTCGGACTTTCTGGGACTTTTGGACTTTGGACTTTGGGACTTTCGGACTTTGGACTTTCGGACTTTTAACAGGACTTTGGACTTTTCTTGGACTTTCAGCCTAATGGGGGACTTTGAGGACTTTTCGGACTTTTGCGCTTCAAACCCCGGACTTTAAGGACTTTGGACTTTGGACTTTGGACTTTTGGACTTTGGACTTTGGGACTTTGGACTTTGGACTTTACGCAGGGACTTTCTGGACTTTGGACTTTCGGCGGACTTTTGGACTTTTGGACTTTGATGCGGACTTTTTGGACTTTGGACTTTCTGGACTTTAAAGGACTTTCGGACTTTCTGGACTTTGGACTTTTCGCCATGGGGACTTTATGGCCTTACGGACTTTGGGACTTTAAAGCGGGACTTTTGGACTTTGGACTTTCAGGACTTTGGGGGACTTTATAGGGACTTTAGGAACTGGGAGTAGCCGGGGGACTTTTGGACTTTGGACTTTACAGGGACTTTCGAGGGACTTTCGCGTGGACTTTGGACTTTCAATGGGACTTTAATGGACTTTTGGACTTTGGGACTTTCAGGACTTTAGGACTTTGTTAGCGGGATGGGACTTTCGGACTTTCGGAGGGACTTTTCGGACTTTGAGGACTTTGGGACTTTGGACTTTGGACTTTTCCGGGACTTTCGCCTTGGAAAGGGACTTTGGACTTTGGACTTTGTCGGACTTTGGACTTTACCCGGACTTTGGACTTTGGACTTTGTGGACTTTCTGATGGACTTTGAAGGAGTGGACTTTGGACTTTACAGGACTTTAGCGGACTTTTGAGGGACTTTGGACTTTGGACTTTCGGACTTTAATATAGGACTTTAGGACTTTGGCACGGACTTTGCAGGACTTTGGACTTTGGACTTTGGACTTTGGACTTTGGGACTTT"
motif = "GGACTTTGG"


def find_motif_index(inputDNA: str,motif: str):
    output = []
    for i in range(0,len(inputDNA)):
        if motif == inputDNA[i:len(motif)+i]:
            print("motif found in:" + str(i+1))
            print(inputDNA[i:len(motif)+i])
            output.append(i+1)
    return output

indecies = find_motif_index(InputDNA,motif)

for i in indecies:
    print(i, end=" ")